name: Docker C++ CI

on:
  push:
    branches: [ main, lab6-docker ]
  pull_request:
    branches: [ main, lab6-docker ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t lab6docker:latest .

      - name: Run unit tests in Docker
        run: docker run --rm lab6docker:latest ./build/test_lab
